name: 'Build and Publish'

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install frontend dependencies
        run: npm install

      - name: Get package version
        id: package-version
        shell: pwsh
        run: |
          $packageJson = Get-Content "package.json" | ConvertFrom-Json
          $version = $packageJson.version
          echo "version=v$version" >> $env:GITHUB_OUTPUT
          echo "raw_version=$version" >> $env:GITHUB_OUTPUT
          echo "Package version: $version"

      - name: Debug version info
        run: |
          echo "Tag version: ${{ steps.package-version.outputs.version }}"
          echo "Raw version: ${{ steps.package-version.outputs.raw_version }}"

      - name: Build and release
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
        with:
          tagName: ${{ steps.package-version.outputs.version }}
          releaseName: 'Release ${{ steps.package-version.outputs.version }}'
          releaseDraft: false
          prerelease: false
          releaseBody: 'See the assets to download this version and install.'
          includeUpdaterJson: true
          updaterJsonPreferNsis: true
          updaterJsonKeepUniversal: true
